server:
  port: 8000

spring:
  application:
    name: cloud-chat

  datasource:
    username: root
    password: 123456
    url: jdbc:mysql:// 192.168.133.248/matchChat?characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource


  cloud:
    nacos:
      server-addr: 192.168.133.248:8848


  data:
    mongodb:
      uri: mongodb://192.168.133.248:27017/webchat

  redis:
    host: 192.168.133.248
    port: 6379
    timeout: 10s