server:
  port: 470
spring:
  application:
    name: email

  mail:
    default-encoding: utf-8
    host: smtp.qq.com
    username: 2625727808@qq.com
    password: sdhxtxzllumndihf  #个人邮箱key
    port: 465
    properties:
      mail:
        smtp:
          ssl:
            enable: true
            required: true
          auth: true
        debug: true



  rabbitmq:
    host: 192.168.133.248
    port: 5672
    username: root
    password: 123456
    virtual-host: /
    listener:
      simple:
        acknowledge-mode: manual   #开启手动应答


    ####################################################################
    #||||||||||||||||||||||| redis |||||||||||||||||||||||||||||||||||||
  redis:
    host: 192.168.133.248
    port: 6379
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

  #+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
  #===================================================================