server:
  port: 7000




spring:
  application:
    name: cloud-user
  profiles:
    active: service

  cloud:
    nacos:
      server-addr: 192.168.133.248:8848

####################################################################
#|||||||||||||||||||||||swagger|||||||||||||||||||||||||||||||||||||
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#===================================================================